server.port=8080
spring.application.name=video-encoding-microservice
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/videojobs}
spring.datasource.username=${DATABASE_USER:appuser}
spring.datasource.password=${DATABASE_PASS:securepass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
management.endpoints.web.exposure.include=health,info
thread.pool.size=${THREAD_POOL_SIZE:8}
